# .github/workflows/ci.yml

name: CI

# ─── 必ず on: をここに書く ─────────────────────────────
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build dependencies for PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libyaml-dev

      - name: Install rye
        run: |
          python -m pip install --upgrade pip
          pip install rye

      - name: Install dependencies
        run: |
          rye sync

      - name: Run tests
        run: |
          rye run test
