name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python and rye
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install rye
        run: |
          python -m pip install --upgrade pip
          pip install rye-up
      - name: Install dependencies
        run: |
          rye sync   # pyproject.toml の deps をインストール
      - name: Run tests
        run: |
          rye run test
