# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel cython

      - name: Install rye
        run: pip install rye

      - name: Install dependencies
        run: rye install

      - name: Run tests
        run: rye run test
